export const Products = [
  {
    id: 1,
    name: "Sofa",
    description: "A comfortable sofa for your living room.",
    price: 599.99,
    image: "https://www.ikea.com/us/en/images/products/friheten-sleeper-sectional-3-seat-w-storage-skiftebo-dark-gray__0175610_pe328883_s5.jpg?f=xl",
    type: "Living Room Furniture",
  },
  {
    id: 2,
    name: "Dining Table",
    description: "Elegant dining table for family gatherings.",
    price: 349.99,
    image: "https://www.ikea.com/us/en/images/products/nordviken-nordviken-table-and-6-chairs-antique-stain-antique-stain__0941064_pe795320_s5.jpg?f=s",
    type: "Dining Room Furniture",
  },
  {
    id: 3,
    name: "Bed Frame",
    description: "Stylish bed frame for a good night's sleep.",
    price: 799.99,
    image: "https://www.ikea.com/us/en/images/products/slattum-upholstered-bed-frame-knisa-light-gray__0768244_pe754388_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 4,
    name: "Coffee Table",
    description: "Modern coffee table for your living space.",
    price: 149.99,
    image: "https://www.ikea.com/us/en/images/products/vittsjoe-coffee-table-black-brown-glass__0135348_pe292039_s5.jpg?f=s",
    type: "Living Room Furniture",
  },
  {
    id: 5,
    name: "Wardrobe",
    description: "Spacious wardrobe for storing your clothes.",
    price: 499.99,
    image: "https://www.ikea.com/us/en/images/products/pax-bergsbo-wardrobe-dark-gray-dark-gray__1154692_pe886251_s5.jpg?f=m",
    type: "Bedroom Furniture",
  },
  {
    id: 6,
    name: "Bookshelf",
    description: "A wooden bookshelf for your home library.",
    price: 249.99,
    image: "https://www.ikea.com/us/en/images/products/kallax-shelf-unit-white__0644757_pe702939_s5.jpg?f=s",
    type: "Living Room Furniture",
  },
  {
    id: 7,
    name: "Dresser",
    description: "A dresser with multiple drawers for your bedroom.",
    price: 329.99,
    image: "https://www.ikea.com/us/en/images/products/bjoerksnaes-5-drawer-chest-birch__0598056_pe677425_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 8,
    name: "Bar Stools",
    description: "Set of bar stools for your kitchen or bar area.",
    price: 89.99,
    image: "https://www.ikea.com/us/en/images/products/stig-bar-stool-with-backrest-black-black__0948110_pe798867_s5.jpg?f=s",
    type: "Kitchen Furniture",
  },
  {
    id: 9,
    name: "Office Desk",
    description: "A sleek desk for your home office.",
    price: 299.99,
    image: "https://www.ikea.com/us/en/images/products/gladhoejden-nilserik-desk-sit-stand-support-white-dark-blue__1155438_pe886634_s5.jpg?f=s",
    type: "Home Office Furniture",
  },
  {
    id: 10,
    name: "Outdoor Patio Set",
    description: "Outdoor furniture set for your patio or garden.",
    price: 799.99,
    image: "https://www.ikea.com/us/en/images/products/askholmen-table-2-chairs-outdoor-light-brown-stained__0735576_pe740060_s5.jpg?f=s",
    type: "Outdoor Furniture",
  },
  {
    id: 11,
    name: "Sectional Sofa",
    description: "A versatile sectional sofa for your living space.",
    price: 899.99,
    image:
      "https://www.ikea.com/us/en/images/products/finnala-corner-sleeper-sofa-5-seat-with-chaise-dalstorp-multicolor__0725562_pe734946_s5.jpg?f=s",
    type: "Living Room Furniture",
  },
  {
    id: 12,
    name: "TV Stand",
    description:
      "Sleek TV stand with ample storage for your entertainment area.",
    price: 299.99,
    image:
      "https://www.ikea.com/us/en/images/products/lack-tv-unit-black-brown__0955264_pe803706_s5.jpg?f=s",
    type: "Living Room Furniture",
  },
  {
    id: 13,
    name: "Coffee Table Set",
    description: "Matching coffee table set for a cohesive look.",
    price: 249.99,
    image:
      "https://www.ikea.com/us/en/images/products/vittsjoe-nesting-tables-set-of-2-black-brown-glass__0735687_pe740087_s5.jpg?f=s",
    type: "Living Room Furniture",
  },
  {
    id: 14,
    name: "Floor Lamp",
    description: "Elegant floor lamp to illuminate your living room.",
    price: 129.99,
    image:
      "https://www.ikea.com/us/en/images/products/trindsnoe-floor-lamp-white-metal-birch-veneer__1164308_pe902206_s5.jpg?f=m",
    type: "Living Room Furniture",
  },
  {
    id: 15,
    name: "Accent Chair",
    description: "Stylish accent chair to complement your living room decor.",
    price: 179.99,
    image:
      "https://www.ikea.com/us/en/images/products/strandmon-wing-chair-skiftebo-yellow__0325450_pe517970_s5.jpg?f=s",
    type: "Living Room Furniture",
  },
  {
    id: 16,
    name: "Queen Bed",
    description: "A comfortable queen-sized bed for a good night's sleep.",
    price: 699.99,
    image: "https://www.ikea.com/us/en/images/products/malm-bed-frame-high-black-brown-luroey__0638608_pe699032_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 17,
    name: "Nightstand",
    description: "A stylish nightstand with storage for your bedroom essentials.",
    price: 99.99,
    image: "https://www.ikea.com/us/en/images/products/gladom-tray-table-red__0568691_pe665565_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 18,
    name: "Dresser Set",
    description: "Matching dresser set with mirror for your bedroom.",
    price: 349.99,
    image: "https://www.ikea.com/us/en/images/products/hauga-storage-combination-gray__0914341_pe783950_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 19,
    name: "Wardrobe Closet",
    description: "Spacious wardrobe closet with sliding doors.",
    price: 599.99,
    image: "https://www.ikea.com/us/en/images/products/pax-hasvik-wardrobe-dark-gray-dark-gray__1119872_pe873635_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 20,
    name: "Chest of Drawers",
    description: "A chest of drawers with multiple storage compartments.",
    price: 249.99,
    image: "https://www.ikea.com/us/en/images/products/hemnes-8-drawer-dresser-white-stain__0627346_pe693299_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 21,
    name: "Bedside Table",
    description: "Compact bedside table with a drawer for your bedroom.",
    price: 79.99,
    image: "https://www.ikea.com/us/en/images/products/yttervag-nightstand-gray-brown__1250458_pe923747_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 22,
    name: "King Bed",
    description: "A luxurious king-sized bed for ultimate comfort.",
    price: 899.99,
    image: "https://www.ikea.com/us/en/images/products/nordli-bed-with-headboard-and-storage-anthracite__1151020_pe884726_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 23,
    name: "Vanity Set",
    description: "Elegant vanity set with a mirror and stool for your bedroom.",
    price: 299.99,
    image: "https://www.ikea.com/us/en/images/products/idanaes-coffee-table-dark-brown-stained__1161066_pe889274_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 24,
    name: "Storage Bench",
    description: "A storage bench with seating and hidden storage space.",
    price: 149.99,
    image: "https://www.ikea.com/us/en/images/products/tolkning-bench-with-storage-handmade-rattan__1098691_pe865484_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },
  {
    id: 25,
    name: "Full Bed",
    description: "A cozy full-sized bed for a restful night's sleep.",
    price: 599.99,
    image: "https://www.ikea.com/us/en/images/products/neiden-bed-frame-pine__0749131_pe745500_s5.jpg?f=s",
    type: "Bedroom Furniture",
  },

  {
    id: 26,
    name: "Extendable Dining Table",
    description: "An extendable dining table to accommodate more guests.",
    price: 499.99,
    image: "https://www.ikea.com/us/en/images/products/nordviken-drop-leaf-table-black__0714209_pe729967_s5.jpg?f=s",
    type: "Dining Room Furniture",
  },
  {
    id: 27,
    name: "Dining Chairs (Set of 4)",
    description: "Set of 4 dining chairs with comfortable seating.",
    price: 199.99,
    image: "https://www.ikea.com/us/en/images/products/moerbylanga-tobias-table-and-4-chairs-oak-veneer-brown-stained-brown-red-chrome-plated__1143383_pe881484_s5.jpg?f=m",
    type: "Dining Room Furniture",
  },
  {
    id: 28,
    name: "Buffet Sideboard",
    description: "A stylish buffet sideboard for serving and storage.",
    price: 349.99,
    image: "https://www.ikea.com/us/en/images/products/malsjoe-sideboard-black-stained__0644409_pe702649_s5.jpg?f=s",
    type: "Dining Room Furniture",
  },
  {
    id: 29,
    name: "Bar Cabinet",
    description: "Bar cabinet with wine storage and glass holders.",
    price: 299.99,
    image: "https://www.ikea.com/us/en/images/products/fjaellbo-sideboard-black__1129167_pe891018_s5.jpg?f=s",
    type: "Dining Room Furniture",
  },
  {
    id: 30,
    name: "Dining Table with Bench",
    description: "Dining table with a bench for a rustic look.",
    price: 549.99,
    image: "https://www.ikea.com/us/en/images/products/ekedalen-ekedalen-table-with-2-chairs-and-bench-dark-brown-orrsta-light-gray__0737694_pe741214_s5.jpg?f=s",
    type: "Dining Room Furniture",
  },
  {
    id: 31,
    name: "China Cabinet",
    description: "Elegant china cabinet with glass doors for display.",
    price: 599.99,
    image: "https://www.ikea.com/us/en/images/products/hemnes-glass-door-cabinet-with-3-drawers-white-stain-light-brown__0805255_pe769478_s5.jpg?f=s",
    type: "Dining Room Furniture",
  },
  {
    id: 32,
    name: "Round Dining Table",
    description: "Round dining table for a cozy dining experience.",
    price: 329.99,
    image: "https://www.ikea.com/us/en/images/products/mariedamm-table-black-marble-effect__0916869_pe785444_s5.jpg?f=s",
    type: "Dining Room Furniture",
  },
  {
    id: 33,
    name: "Counter Height Stools (Set of 2)",
    description: "Set of 2 counter height stools for a modern kitchen.",
    price: 129.99,
    image: "https://www.ikea.com/us/en/images/products/haverud-dalfred-table-and-2-stools-black-black__1028674_pe835477_s5.jpg?f=s",
    type: "Dining Room Furniture",
  },
  {
    id: 34,
    name: "Dining Bench",
    description: "Dining bench for versatile seating options.",
    price: 79.99,
    image: "https://www.ikea.com/us/en/images/products/skogsta-bench-acacia__0365463_pe548271_s5.jpg?f=m",
    type: "Dining Room Furniture",
  },
  {
    id: 35,
    name: "Wine Rack",
    description: "Wall-mounted wine rack for your wine collection.",
    price: 49.99,
    image: "https://www.ikea.com/us/en/images/products/hutten-9-bottle-wine-rack-solid-wood__0711110_pe727966_s5.jpg?f=s",
    type: "Dining Room Furniture",
  }
  
];
