export const BedroomProducts = [
    {
        id: 16,
        name: "Queen Bed",
        description: "A comfortable queen-sized bed for a good night's sleep.",
        price: 699.99,
        image: "https://www.ikea.com/us/en/images/products/malm-bed-frame-high-black-brown-luroey__0638608_pe699032_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      {
        id: 17,
        name: "Nightstand",
        description: "A stylish nightstand with storage for your bedroom essentials.",
        price: 99.99,
        image: "https://www.ikea.com/us/en/images/products/gladom-tray-table-red__0568691_pe665565_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      {
        id: 18,
        name: "Dresser Set",
        description: "Matching dresser set with mirror for your bedroom.",
        price: 349.99,
        image: "https://www.ikea.com/us/en/images/products/hauga-storage-combination-gray__0914341_pe783950_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      {
        id: 19,
        name: "Wardrobe Closet",
        description: "Spacious wardrobe closet with sliding doors.",
        price: 599.99,
        image: "https://www.ikea.com/us/en/images/products/pax-hasvik-wardrobe-dark-gray-dark-gray__1119872_pe873635_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      {
        id: 20,
        name: "Chest of Drawers",
        description: "A chest of drawers with multiple storage compartments.",
        price: 249.99,
        image: "https://www.ikea.com/us/en/images/products/hemnes-8-drawer-dresser-white-stain__0627346_pe693299_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      {
        id: 21,
        name: "Bedside Table",
        description: "Compact bedside table with a drawer for your bedroom.",
        price: 79.99,
        image: "https://www.ikea.com/us/en/images/products/yttervag-nightstand-gray-brown__1250458_pe923747_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      {
        id: 22,
        name: "King Bed",
        description: "A luxurious king-sized bed for ultimate comfort.",
        price: 899.99,
        image: "https://www.ikea.com/us/en/images/products/nordli-bed-with-headboard-and-storage-anthracite__1151020_pe884726_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      {
        id: 23,
        name: "Vanity Set",
        description: "Elegant vanity set with a mirror and stool for your bedroom.",
        price: 299.99,
        image: "https://www.ikea.com/us/en/images/products/idanaes-coffee-table-dark-brown-stained__1161066_pe889274_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      {
        id: 24,
        name: "Storage Bench",
        description: "A storage bench with seating and hidden storage space.",
        price: 149.99,
        image: "https://www.ikea.com/us/en/images/products/tolkning-bench-with-storage-handmade-rattan__1098691_pe865484_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      {
        id: 25,
        name: "Full Bed",
        description: "A cozy full-sized bed for a restful night's sleep.",
        price: 599.99,
        image: "https://www.ikea.com/us/en/images/products/neiden-bed-frame-pine__0749131_pe745500_s5.jpg?f=s",
        type: "Bedroom Furniture",
      },
      
]