export const DinigRoom = [
    {
        id: 26,
        name: "Extendable Dining Table",
        description: "An extendable dining table to accommodate more guests.",
        price: 499.99,
        image: "https://www.ikea.com/us/en/images/products/nordviken-drop-leaf-table-black__0714209_pe729967_s5.jpg?f=s",
        type: "Dining Room Furniture",
      },
      {
        id: 27,
        name: "Dining Chairs (Set of 4)",
        description: "Set of 4 dining chairs with comfortable seating.",
        price: 199.99,
        image: "https://www.ikea.com/us/en/images/products/moerbylanga-tobias-table-and-4-chairs-oak-veneer-brown-stained-brown-red-chrome-plated__1143383_pe881484_s5.jpg?f=m",
        type: "Dining Room Furniture",
      },
      {
        id: 28,
        name: "Buffet Sideboard",
        description: "A stylish buffet sideboard for serving and storage.",
        price: 349.99,
        image: "https://www.ikea.com/us/en/images/products/malsjoe-sideboard-black-stained__0644409_pe702649_s5.jpg?f=s",
        type: "Dining Room Furniture",
      },
      {
        id: 29,
        name: "Bar Cabinet",
        description: "Bar cabinet with wine storage and glass holders.",
        price: 299.99,
        image: "https://www.ikea.com/us/en/images/products/fjaellbo-sideboard-black__1129167_pe891018_s5.jpg?f=s",
        type: "Dining Room Furniture",
      },
      {
        id: 30,
        name: "Dining Table with Bench",
        description: "Dining table with a bench for a rustic look.",
        price: 549.99,
        image: "https://www.ikea.com/us/en/images/products/ekedalen-ekedalen-table-with-2-chairs-and-bench-dark-brown-orrsta-light-gray__0737694_pe741214_s5.jpg?f=s",
        type: "Dining Room Furniture",
      },
      {
        id: 31,
        name: "China Cabinet",
        description: "Elegant china cabinet with glass doors for display.",
        price: 599.99,
        image: "https://www.ikea.com/us/en/images/products/hemnes-glass-door-cabinet-with-3-drawers-white-stain-light-brown__0805255_pe769478_s5.jpg?f=s",
        type: "Dining Room Furniture",
      },
      {
        id: 32,
        name: "Round Dining Table",
        description: "Round dining table for a cozy dining experience.",
        price: 329.99,
        image: "https://www.ikea.com/us/en/images/products/mariedamm-table-black-marble-effect__0916869_pe785444_s5.jpg?f=s",
        type: "Dining Room Furniture",
      },
      {
        id: 33,
        name: "Counter Height Stools (Set of 2)",
        description: "Set of 2 counter height stools for a modern kitchen.",
        price: 129.99,
        image: "https://www.ikea.com/us/en/images/products/haverud-dalfred-table-and-2-stools-black-black__1028674_pe835477_s5.jpg?f=s",
        type: "Dining Room Furniture",
      },
      {
        id: 34,
        name: "Dining Bench",
        description: "Dining bench for versatile seating options.",
        price: 79.99,
        image: "https://www.ikea.com/us/en/images/products/skogsta-bench-acacia__0365463_pe548271_s5.jpg?f=m",
        type: "Dining Room Furniture",
      },
      {
        id: 35,
        name: "Wine Rack",
        description: "Wall-mounted wine rack for your wine collection.",
        price: 49.99,
        image: "https://www.ikea.com/us/en/images/products/hutten-9-bottle-wine-rack-solid-wood__0711110_pe727966_s5.jpg?f=s",
        type: "Dining Room Furniture",
      }
      
]